---
title: "progress-report-NickDeReus-ISU"
output: html_document
date: "2024-12-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Begin
```{r}
library(rvest)
library(tidyverse)
# install.packages('Lahman')
library(Lahman)
data(dataframe = HallOfFame, package = "Lahman")
```

```{r}
url <- "https://www.baseball-reference.com/awards/hof_2024.shtml"
html <- read_html(url)
html
```
```{r}
HoF2024 <- html_table(html)[[1]]

head(HallOfFame)
HoF2024 %>% data.frame %>% head()

```
```{r}
createID <- function(Name, othervector){
  # Space_Index <- match(" ", Name)
  Name <- as.character(Name)
  Name <- str_replace(Name, "X-", "")
  firstPart <-  strsplit(Name, " ")[[1]][1]
  secondPart <- strsplit(Name, " ")[[1]][2]
  
  ID <- paste( tolower( secondPart), tolower(substr( firstPart, 1,2)), sep = "")
  
  # othervector <- othervector$PlayerID
  
  # if (!paste(ID, "01", sep = "") %in% othervector) return( paste(ID, "01", sep = "") )
  # else if (!paste(ID, "02", sep = "") %in% othervector) return( paste(ID, "02", sep = "") )
  # else if (!paste(ID, "03", sep = "") %in% othervector) return( paste(ID, "03", sep = "") )
  
  return( paste(ID, "01", sep = "") )
}

playerIDVector <- pull(HallOfFame, playerID)

HoF2024_clean <- HoF2024 %>% data.frame() %>% group_by(Var.2) %>% filter(Var.2 != "Name") %>% summarize(
  playerID = Var.2 %>% createID( playerIDVector),
  votes = Var.4 %>% as.numeric(),
  # Vote_Percent = Var.5 %>% parse_number()/100,
  # ballots = round(votes / Vote_Percent),
  # needed = ceiling(ballots * .75),
  ballots = 385,
  needed = 289,
  inducted = if_else(votes > needed, "Y", "N"),
  yearID = 2024
)

HoF2024_clean<- HoF2024_clean %>% select(-Var.2)
HoF2024_clean
```
```{r}
HallOfFame %>% bind_rows(HoF2024_clean)


```

